### ISSUE TITLE
Failed to launch SAM Local

### ISSUE THREAD

**Issue by DHer007** [aws/aws-toolkit-eclipse#104]
Hi,
I got a problem as attached when run "Debug on AWS SAM Local" on Eclipse. Could you please help check it?
[debug].log](https://github.com/aws/aws-toolkit-eclipse/files/1914796/debug.log)

Any resolution are very appreciate.

**Comment by zhangzhx** [comment]
I can reproduce this issue. Will send a fix in the next version. BTW, what sam local version you are running on?

**Comment by NickHdx** [comment]
Thanks for your feedback. I have resolved this issue by setting below variables in User variables config of Windows OS so that eclipse can connect to docker daemon. BTW, sam local 0.2.11 was installed on Windows 7 on my PC and running in Docker Toolbox.
@SETX DOCKER_TLS_VERIFY 1
@SETX DOCKER_HOST tcp://192.168.99.100:2376
@SETX DOCKER_CERT_PATH %USERPROFILE%\.docker\machine\machines\default
@SETX DOCKER_MACHINE_NAME default
@SETX COMPOSE_CONVERT_WINDOWS_PATHS true

Also, you can get these variables by running cmd: docker-machine env --shell cmd default

And I get another error when running "Debug on AWS SAM Local" on Eclipse. The error massage eclipse console outputted is "unable to use container host config override file from '$HOME/.config/aws-sam-local/container-config.json': HOME env variable is not set".

I found some suggestions in this post: https://github.com/awslabs/aws-sam-cli/issues/82 but all of them didn't work. Could you please help on this?

**Comment by cpandey05** [comment]
I am facing similar issue but on CENTOS 7 and SAM CLI, version 0.14.1
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product
com.amazonaws.eclipse.core.exceptions.AwsActionException
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:159)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.buildSamLocalCommandLine(SamLocalDelegate.java:243)
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:105)
	... 5 more

**Comment by vinayak-kaviskar** [comment]
I am facing the same issue on ubuntu 18.04, my sam version is 0.16.0,  can anybody please help in this issue?
