### ISSUE TITLE
Error uploading ______.jar: Unable to complete transfer: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by psubrownie** [aws/aws-toolkit-eclipse#123]
I'm not sure where the first error is but in Eclipse I cannot upload a lambda function.  Unclear if its a S3 issue or Lambda
`java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.amazonaws.util.Md5Utils.md5AsBase64(Md5Utils.java:104)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1647)
	at com.amazonaws.eclipse.lambda.upload.wizard.util.UploadFunctionUtil.performFunctionUpload(UploadFunctionUtil.java:95)
	at com.amazonaws.eclipse.lambda.upload.wizard.UploadFunctionWizard.doFinish(UploadFunctionWizard.java:111)
	at com.amazonaws.eclipse.core.plugin.AbstractAwsJobWizard$1.run(AbstractAwsJobWizard.java:35)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException cannot be found by com.amazonaws.eclipse.javasdk_1.11.248
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
`
session Data:
`eclipse.buildId=4.9.0.I20180906-0745
java.version=11
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product
`

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. Java 11 is not supported by far. The desired Java version is Java 8.

**Comment by mystygage** [comment]
I also fell into this trap. It would be great if this restriction (use Java 8-10) were visible [here](https://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/setup-install.html) or [here](https://github.com/aws/aws-toolkit-eclipse/blob/master/README.md).

**Comment by william-ricaurte-skymate** [comment]
What is the plan for supporting Java 11? Some IDEs can not upload lambda functions due this issue. (JAXB classes were deprecated)

**Comment by zhangzhx** [comment]
Hi @william-ricaurte-skymate ,

Thanks for reaching out to us. We are more focused on JetBrains plugins at the moment. The support of Java 11 in Eclipse has a low priority. The [AWS Toolkit for JetBrains](https://plugins.jetbrains.com/plugin/11349-aws-toolkit) has fully supported SAM local running/debugging of Java/Python. We recommend SAM users to switch to AWS Toolkit for JetBrains for better support.

If you have reasons why not switching to IntelliJ, can you let us know? Thanks.

**Comment by guss77** [comment]
@zhangzhx - Eclipse is a good IDE with a lot of useful built-in features and a lot of third-party plugins. For my use cases Eclipse is better featured, more configurable, faster and more comfortable as I've been working with it a long time now. It integrates better with my Linux-based operating system (open file dialog boxes see network shares, etc). I also believe their out-of-the-box keyboard shortcuts are superior and I can't get used to the JetBrains way of doing things.

JetBrains is a commercial software with an expensive license - the non-crippled version is $500 for the first year. This is too expensive for a lot of developers and we already pay quite a bit to Amazon for AWS service.

Java 8 is 4 versions behind the current GA version with Eclipse 2019-06 supporting Java 12. Amazon offer support for Java 11 across their entire range of products including the Corretto JDK distribution.

The fix for this issue sounds to be pretty small - just add JAXB as a dependency to the plugin and be done with it.

If Amazon decides not to support Eclipse, just say so and drop this project - stringing us along with "Yes, we support Eclipse - as long as you use this ancient version on this ancient installation" is not OK. Java 8 and Eclipse 4.4 were released in 2014.

**Comment by guss77** [comment]
I have found a workaround for this issue:
1. Locate a copy of the JAXB jar. After you have used it in a Maven project, you can find one using `ls ~/.m2/repository/javax/xml/bind/jaxb-api/*/*[0-9].jar`
2. Run eclipse with the `-dev` command ([See here](https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Frunning_eclipse.htm)) followed by the path to the JAXB jar.

The following worked for me:

``
eclipse -dev $(ls ~/.m2/repository/javax/xml/bind/jaxb-api/*/*[0-9].jar | tail -n1)
```

**Comment by renschler** [comment]
> I also fell into this trap. It would be great if this restriction (use Java 8-10) were visible [here](https://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/setup-install.html) or [here](https://github.com/aws/aws-toolkit-eclipse/blob/master/README.md).

it's not clear in the docs that *only* java 1.8 will work. ("To contribute to the AWS Toolkit for Eclipse, you need to have at least these requirements met."...)

I tried to reinstall eclipse from scratch to see if I could get things to work with corretto 8 but it wouldn't let me, I had to select java-11 or greater during install. 
![Screen Shot 2020-10-07 at 7 20 47 PM](https://user-images.githubusercontent.com/3973468/95407612-5ceb2200-08d2-11eb-91a6-0c64106e76ab.png)

Then, after install, even when I set eclipse and the project to use corretto8 as the JRE, I hit the same error. Presumably because I wasn't able to select java-8 when I first installed eclipse.
![Screen Shot 2020-10-07 at 7 23 12 PM](https://user-images.githubusercontent.com/3973468/95407707-9cb20980-08d2-11eb-87b5-98990e963225.png)

**Comment by gjblajian** [comment]
> I have found a workaround for this issue:
> 
> 1. Locate a copy of the JAXB jar. After you have used it in a Maven project, you can find one using `ls ~/.m2/repository/javax/xml/bind/jaxb-api/*/*[0-9].jar`
> 2. Run eclipse with the `-dev` command ([See here](https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Frunning_eclipse.htm)) followed by the path to the JAXB jar.
> 
> The following worked for me:
> 
> ```
> eclipse -dev $(ls ~/.m2/repository/javax/xml/bind/jaxb-api/*/*[0-9].jar | tail -n1)
> ```

guss77's suggestion worked for me, but I was not happy launching eclipse from the command prompt, so I added the following entry to the eclipse.ini file then tested uploading to AWS lambda and it worked

`-startup
plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1300.v20200819-0940
**-dev
H:\cust\eclipse\jee-2019-12\plugins\jaxb-api-2.3.1.jar**
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_14.0.2.v20200815-0932/jre/bin
-product
org.eclipse.epp.package.jee.product
-showsplash
org.eclipse.epp.package.common
--launcher.defaultAction
openFile
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
`
