### ISSUE TITLE
Unable to launch SAM local from eclipse on CENTOS7

### ISSUE THREAD

**Issue by cpandey05** [aws/aws-toolkit-eclipse#142]
I installed AWS plugin for eclipse CENTOS 7 with SAM CLI, version 0.14.1. I am trying to debug a sample app from https://github.com/aws-samples/aws-sam-java-rest , but the debug launch  fails with following error (This may be related to https://github.com/aws/aws-toolkit-eclipse/issues/104 but that is for other environment and was solved by setting some variables, so opening a new one here)

eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments: -product org.eclipse.epp.package.jee.product
Command-line arguments: -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product
com.amazonaws.eclipse.core.exceptions.AwsActionException
at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:159)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.buildSamLocalCommandLine(SamLocalDelegate.java:243)
at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:105)
... 5 more

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. It seems to be Eclipse Debugger has not been successfully launched. 

By the way, we are deprioritizing Eclipse plugin development and focusing on JetBrains IDEs support. Here is the [AWS toolkit for JetBrains](https://plugins.jetbrains.com/plugin/11349-aws-toolkit). We'd like you to give it a try and let us know how you feel. It will provide better support and faster bug fix.
