### ISSUE TITLE
unable  to deploy webapps in AWS

### ISSUE THREAD

**Issue by uddinayazsk** [aws/aws-toolkit-eclipse#187]
After adding credentials (access key from AWS) , not able to elastic bean stalk in my server console so that unable to run, kindly help on this , thanks

**Comment by uddinayazsk** [comment]
error log:failed to lunch SAM local
But it is not maven project

Details
============
com.amazonaws.eclipse.core.exceptions.AwsActionException: The project must be a Maven project with a pom.xml file in the root!
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:159)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1020)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: The project must be a Maven project with a pom.xml file in the root!
	at com.amazonaws.eclipse.core.util.MavenBuildLauncher.validateParameters(MavenBuildLauncher.java:131)
	at com.amazonaws.eclipse.core.util.AbstractApplicationLauncher.launchAsync(AbstractApplicationLauncher.java:51)
	at com.amazonaws.eclipse.core.util.AbstractApplicationLauncher.launch(AbstractApplicationLauncher.java:60)
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:100)
	... 5 more

**Comment by uddinayazsk** [comment]
Evening I am getting same error when  i tried to deploy maven project

**Comment by kiiadi** [comment]
@uddinayazsk would like to understand a bit more about the problem you're seeing, are you saying you have a beanstalk project already - or was it a project you created through the toolkit? 
The exception suggests it can't find your pom.xml - what does your project structure look like? can you show me some screen-shots of the workflow so I can understand further?

It'd also be useful to understand versions of:
Eclipse
AWS Toolkit
Your OS
the SAM CLI

**Comment by uddinayazsk** [comment]
Hi, though I have deployed that war of project successfully(http://cvandsamplegitayaz-env.eba-3azpkvdf.us-east-2.elasticbeanstalk.com/) , but i am unable to deploy from eclipse by following this procedure.
OS-windows 10
IDE -Eclipse 2019-06
[AWSdeployErrorDoc1.docx](https://github.com/aws/aws-toolkit-eclipse/files/4578574/AWSdeployErrorDoc1.docx)

kindly look at this
if i run 
AWS SAM local
of course build is successful but ended in failed to lunch SAM local
PFA
[AWSdeployErrorDoc1.docx](https://github.com/aws/aws-toolkit-eclipse/files/4578576/AWSdeployErrorDoc1.docx)

**Comment by kiiadi** [comment]
What version of SAM do you have? Can you run `sam --version` locally?
