### ISSUE TITLE
AWS Sam Local eclipse toolkit 

### ISSUE THREAD

**Issue by speedysingh786** [aws/aws-toolkit-eclipse#189]
com.amazonaws.eclipse.core.exceptions.AwsActionException
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:159)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1020)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:116)
	... 5 more

eclipse.buildId=4.12.0.I20190605-1800
java.version=1.8.0_211
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/C:/Users/P7110672/lambda-research/ -product org.eclipse.epp.package.jee.product

**Comment by kiiadi** [comment]
what version of the SAM CLI do you have? can you run `sam --version` ?

**Comment by speedysingh786** [comment]
SAM CLI, version 0.47.0

**Comment by rli** [comment]
At the moment, the Eclipse toolkit does not support the latest version of the SAM CLI.

Until that is fixed, both the [AWS Toolkit for JetBrains](https://plugins.jetbrains.com/plugin/11349-aws-toolkit) and [AWS Toolkit for VS Code](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) have support for the latest SAM CLI versions.

**Comment by arthurlwright** [comment]
What version of SAM CLI is supported?
