### ISSUE TITLE
SimpleDB Explorer doesn't load when running under Java 11

### ISSUE THREAD

**Issue by twasink** [aws/aws-toolkit-eclipse#219]
If you run Eclipse under Java 11, the SimpleDB explorer doesn't load - it just sits on the 'loading' message, and never returns.

Eclipse 2020-09 and above require Java 11 to run (though you can reproduce this behaviour using Java 11 under older versions of Eclipse)

**Comment by twasink** [comment]
I'm happy to investigate this, but I've got very limited experience building Eclipse plugins; some hints on debugging (even just outputting stuff to the error log) would be appreciated

**Comment by eschulma** [comment]
I am running into this with the CodeDeploy plugin as well. Almost certainly, the issue is similar to mine, namely that you are using javax.xml.bind classes that are no longer in Java 11:

`java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.amazonaws.util.Md5Utils.md5AsBase64(Md5Utils.java:104)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1647)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1604)
	at com.amazonaws.eclipse.codedeploy.deploy.util.DeployUtils.createDeployment(DeployUtils.java:112)
	at com.amazonaws.eclipse.codedeploy.deploy.wizard.DeployProjectToCodeDeployWizard$1.run(DeployProjectToCodeDeployWizard.java:74)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException cannot be found by com.amazonaws.eclipse.javasdk_1.11.248
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more`

**Comment by twasink** [comment]
It kind of feels like this project is abandonware; nobody from AWS has contributed to it for a year, and basic issues like this remain unfixed.
