### ISSUE TITLE
Elipse: Failed to launch SAM during debug

### ISSUE THREAD

**Issue by gvallangca** [aws/aws-toolkit-eclipse#236]
To whom it may concern,

I'm running AWS SAM local in Eclipse(Windows 10) through debug mode and it's always throwing a pop-up exception. Please see the captured stack trace below:

com.amazonaws.eclipse.core.exceptions.AwsActionException: Cannot invoke "org.eclipse.ui.console.IOConsole.newOutputStream()" because "samLocalConsole" is null
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:159)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1029)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.console.IOConsole.newOutputStream()" because "samLocalConsole" is null
	at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:116)
	... 5 more

**Comment by gvallangca** [comment]
I had used 3 different versions(2019, 2020, 2021) of Eclipse and all of them throws the same error as mentioned above.

**Comment by arambhat** [comment]
I'm having the same issue when trying to spinoff a aws ec2 instance from a eclipse java project using aws sdk

**Comment by steowens** [comment]
I have the same issue.

**Comment by tgpadua** [comment]
+1
