### ISSUE TITLE
Open Shell on EC2 causes null pointer exception

### ISSUE THREAD

**Issue by jwarder** [aws/aws-toolkit-eclipse#71]
When right clicking on an EC2 instance and clicking "Open Shell" throws a null pointer exception:

![image](https://user-images.githubusercontent.com/4456200/27742545-09699988-5db1-11e7-9bee-95873840bdb1.png)

`java.lang.NullPointerException
	at com.amazonaws.eclipse.ec2.PlatformUtils.getPuttyGenConversionExecutable(PlatformUtils.java:207)
	at com.amazonaws.eclipse.ec2.PlatformUtils.openRemoteShellFromWindows(PlatformUtils.java:194)
	at com.amazonaws.eclipse.ec2.PlatformUtils.openShellToRemoteHost(PlatformUtils.java:150)
	at com.amazonaws.eclipse.ec2.ui.views.instances.OpenShellAction.openInstanceShell(OpenShellAction.java:82)
	at com.amazonaws.eclipse.ec2.ui.views.instances.OpenShellAction.openInstanceShell(OpenShellAction.java:51)
	at com.amazonaws.eclipse.ec2.ui.views.instances.OpenShellAction.run(OpenShellAction.java:46)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)`

`eclipse.buildId=4.7.0.I20170612-0950
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/C:/Users/GCUK-JW/workspaces/eclipse-workspace/ -product org.eclipse.epp.package.jee.product`

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. I could reproduce this on Windows. I will take a look and submit a fix in the next release. Will let you know once it is fixed.

**Comment by zhangzhx** [comment]
This bug has been fixed in the latest release [v201708161930](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201708161930).
